### ISSUE TITLE
i pushed up assignment 2 and 3 and you give me zero why ? 

### ISSUE THREAD

**Issue by Omar-Ashraf-58612** [wbadry/MTE506#7]

**Comment by Omar-Ashraf-58612** [comment]
End waleed,
i pushed up on github assignment 2 and 3 before deadline  and you give me zero 
why ?
omar ashraf 58612 
thank you

**Comment by wbadry** [comment]
Let's have a look at your timeline

![2020-04-12_20-37-51](https://user-images.githubusercontent.com/5664750/79076987-4470c500-7cfe-11ea-8c9b-199ebaf80cf6.png)

![2020-04-12_20-38-38](https://user-images.githubusercontent.com/5664750/79076992-49357900-7cfe-11ea-9d2c-8ebb1f861e9a.png)

![2020-04-12_20-39-48](https://user-images.githubusercontent.com/5664750/79076993-4c306980-7cfe-11ea-8469-c2e3f49dcccb.png)


There is no instance showing you submitted **Assignment 2**. That's the beauty of Github that it records your activities in detail so that I won't miss any effort you did.

For Assignment 3, your mark is corrected and will be updated in the next classwork announcement.

**Comment by Omar-Ashraf-58612** [comment]
this is my assignment 2 , i didn't understand the wrong 
![Untitled](https://user-images.githubusercontent.com/48031651/79113589-83942a00-7d81-11ea-807c-aa613044d29e.png)

**Comment by wbadry** [comment]
I got it. You forked the course and added the assignment to it. I instructed each student to have a **private repository** so your answers can not be copied! This is a public repository.

**Comment by wbadry** [comment]
Make **ONLY One private repository** for all assignments and delete other repositories.
![2020-04-13_13-10-46](https://user-images.githubusercontent.com/5664750/79116273-4bdcb080-7d88-11ea-8cb6-ca9cfc1fcfd9.png)

**Comment by Omar-Ashraf-58612** [comment]
ok. 
what can i do now ? i didn't understand github correctly and i didn't found private repository in github desktop . 
can i push the assignment in my last repository . 
thank you

**Comment by wbadry** [comment]
No worries ya Omar. Check your private repository.
